#!/bin/bash

BASE_DIR=`cd "$(dirname "$0")";pwd`

# https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:ethereum/ethereum
sudo apt-get update
sudo apt-get install -y ethereum

# http://solidity.readthedocs.io/en/develop/installing-solidity.html#binary-packages
sudo snap install solc

# ~/.ethereum restore
"$BASE_DIR"/ethereum-restore
