#!/bin/bash

BASE_DIR=`cd "$(dirname "$0")";pwd`

sudo sudo apt-get install zip unzip

curl -s "https://get.sdkman.io" | bash
source ~/.sdkman/bin/sdkman-init.sh
yes | sdk install java 8u151-oracle
sdk install maven
sdk install gradle

# ~/.m2 restore
"$BASE_DIR"/maven-restore
