#!/bin/bash
set -e
set +x

web3j_ver=2.3.1
web3j_tar_url=https://github.com/web3j/web3j/releases/download/v${web3j_ver}/web3j-${web3j_ver}.tar
web3j_tar=${web3j_tar_url##*/}
web3j_dir=`basename $web3j_tar .tar`
web3j_download_dir=/vagrant/bin

remove_web3j() {
    local d=~/$web3j_dir

    if [ -d "$d" ]
    then
      echo "Removing $d ..."
      rm -rf $d
      rm -f ~/bin/web3j
    fi
}

download_web3j() {
    local d=$web3j_download_dir

    if [ ! -f "$d/$web3j_tar" ]
    then
      echo "Downloading $web3j_tar_url to $d ..."
      mkdir -p $d
      wget -q -c $web3j_tar_url -O $d/$web3j_tar
    fi
}

install_web3j() {
    local f="$web3j_download_dir/$web3j_tar"

    if [ -f "$f" ]
    then
        echo "Installing $f ..."
        mkdir -p ~/$web3j_dir
        tar xf "$f"
        mkdir -p ~/bin
        ln -sf ~/$web3j_dir/bin/web3j ~/bin
    fi
}

remove_web3j
download_web3j
install_web3j
